import type { PassportEntry } from "./types";

const simulatedSource = "Scenario dimostrativo Olbia Yachting Community — dato simulato, non documento reale";

export const demoEntries: PassportEntry[] = [
  { id: "demo-001", date: "2026-09-01", type: "Nota tecnica", title: "Inventario iniziale impianto propulsivo", description: "Scenario demo: motore indicato come Honda BF135. Matricola e ore motore non fornite; da rilevare sul posto.", componentId: "engine", source: simulatedSource, status: "Da verificare", urgency: "Media", internalNotes: "Non associare matricole senza foto targhetta.", demo: true },
  { id: "demo-002", date: "2026-09-02", type: "Documento", title: "Scheda identificativa display", description: "ASE 4.3 inserito nel caso demo. Versione firmware e cablaggio non documentati.", componentId: "display", source: simulatedSource, status: "Da verificare", urgency: "Bassa", internalNotes: "Richiedere foto targhetta e schermata info.", demo: true },
  { id: "demo-003", date: "2026-09-03", type: "Nota tecnica", title: "Rete di bordo dichiarata NMEA 2000", description: "Configurazione usata nel caso dimostrativo. Topologia, terminatori e alimentazione non verificati.", componentId: "nmea", source: simulatedSource, status: "Da verificare", urgency: "Media", internalNotes: "Verificare sullo schema dell'imbarcazione.", demo: true },
  { id: "demo-004", date: "2026-09-04", type: "Foto", title: "Rapporto fotografico — sensore 1", description: "Segnaposto descrittivo: nessuna foto reale allegata. La posizione del sensore va confermata a bordo.", componentId: "fuel-1", source: simulatedSource, status: "Da verificare", urgency: "Media", attachmentName: "foto_sensore_carburante_1_demo.jpg (simulata)", internalNotes: "Non usare come prova fotografica.", demo: true },
  { id: "demo-005", date: "2026-09-05", type: "Foto", title: "Rapporto fotografico — sensore 2", description: "Segnaposto descrittivo: nessuna foto reale allegata. Confrontare cablaggio e lettura con il sensore 1.", componentId: "fuel-2", source: simulatedSource, status: "Da verificare", urgency: "Media", attachmentName: "foto_sensore_carburante_2_demo.jpg (simulata)", internalNotes: "Immagine non presente nel prototipo.", demo: true },
  { id: "demo-006", date: "2026-09-06", type: "Problema segnalato", title: "Lettura carburante instabile — sensore 1", description: "Nel caso demo viene riferita una lettura intermittente. Il sintomo non è stato riprodotto né diagnosticato.", componentId: "fuel-1", source: simulatedSource, status: "Da verificare", urgency: "Alta", internalNotes: "Annotare livello reale e lettura display nello stesso momento.", demo: true },
  { id: "demo-007", date: "2026-09-07", type: "Problema segnalato", title: "Lettura carburante da confrontare — sensore 2", description: "Possibile scostamento riferito nello scenario demo; non sono disponibili misure reali.", componentId: "fuel-2", source: simulatedSource, status: "Da verificare", urgency: "Media", internalNotes: "Verifica con metodo approvato dal costruttore.", demo: true },
  { id: "demo-008", date: "2026-09-08", type: "Nota tecnica", title: "Controllo display ASE 4.3", description: "Attività proposta nello scenario: acquisire foto delle pagine di stato e annotare eventuali codici mostrati.", componentId: "display", source: simulatedSource, status: "Da verificare", urgency: "Media", internalNotes: "Nessun controllo eseguito in questa demo.", demo: true },
  { id: "demo-009", date: "2026-09-09", type: "Intervento", title: "Verifica collegamento NMEA 2000", description: "Intervento pianificato nello scenario per controllare alimentazione bus, connettori e terminazione.", componentId: "nmea", source: simulatedSource, status: "Da verificare", urgency: "Media", internalNotes: "Da svolgere da tecnico qualificato e documentare.", demo: true },
  { id: "demo-010", date: "2026-09-10", type: "Problema segnalato", title: "Richiesta diagnosi Honda BF135", description: "Esempio di richiesta di lettura diagnostica; nessun codice motore reale è presente nei dati demo.", componentId: "engine", source: simulatedSource, status: "Da verificare", urgency: "Alta", internalNotes: "Registrare il codice esatto senza interpretazioni preventive.", demo: true },
  { id: "demo-011", date: "2026-09-11", type: "Ricambio", title: "Sensore carburante — ricambio da identificare", description: "Componente citato come possibile ricambio. Marca, codice, resistenza e compatibilità non forniti.", componentId: "spares", source: simulatedSource, status: "Da verificare", urgency: "Media", internalNotes: "Non ordinare prima della verifica di compatibilità.", demo: true },
  { id: "demo-012", date: "2026-09-12", type: "Ordine", title: "Ordine ricambio carburante — fac-simile", description: "Voce ordine dimostrativa, non trasmessa a fornitori e priva di importi reali.", componentId: "spares", source: simulatedSource, status: "Da verificare", urgency: "Bassa", internalNotes: "Fac-simile non valido per acquisto.", demo: true },
  { id: "demo-013", date: "2026-09-13", type: "Fattura", title: "Materiale elettrico — fac-simile", description: "Esempio di archivio fattura: nessun fornitore, imponibile o documento reale associato.", componentId: "admin", source: simulatedSource, status: "Da verificare", urgency: "Bassa", internalNotes: "Documento non fiscale e non contabile.", demo: true },
  { id: "demo-014", date: "2026-09-14", type: "DDT", title: "DDT cablaggio — fac-simile", description: "Esempio di documento di trasporto simulato. Nessuna consegna reale attestata.", componentId: "admin", source: simulatedSource, status: "Da verificare", urgency: "Bassa", internalNotes: "Verificare i documenti originali prima di archiviare.", demo: true },
  { id: "demo-015", date: "2026-09-15", type: "Nota tecnica", title: "Nota su chiave e control unit", description: "Promemoria demo: documentare la relazione tra chiave, control unit e cablaggio secondo lo schema specifico.", componentId: "electrical", source: simulatedSource, status: "Da verificare", urgency: "Media", internalNotes: "Non scollegare o ponticellare circuiti senza procedura corretta.", demo: true },
  { id: "demo-016", date: "2026-09-16", type: "Intervento", title: "Verifica cablaggio sensori", description: "Controllo proposto; nessuna sostituzione o riparazione è dichiarata come eseguita.", componentId: "electrical", source: simulatedSource, status: "Da verificare", urgency: "Alta", internalNotes: "Fotografare connettori prima e dopo l'eventuale intervento.", demo: true },
  { id: "demo-017", date: "2026-09-17", type: "Problema segnalato", title: "Codice errore motore da acquisire", description: "Caso demo per raccogliere codice diagnostico, condizioni di comparsa e ore motore.", componentId: "engine", source: simulatedSource, status: "Da verificare", urgency: "Alta", internalNotes: "Il codice non è stato fornito: evitare ipotesi.", demo: true },
  { id: "demo-018", date: "2026-09-18", type: "Foto", title: "Rapporto fotografico prima/dopo — esempio", description: "Elemento segnaposto per allegare immagini reali dopo aver acquisito il consenso e verificato la barca.", componentId: "general", source: simulatedSource, status: "Da verificare", urgency: "Bassa", attachmentName: "rapporto_prima_dopo_demo.txt (nessuna immagine reale)", internalNotes: "Sostituire con allegati reali solo dopo acquisizione.", demo: true },
  { id: "demo-019", date: "2026-09-19", type: "Ordine", title: "Materiale elettrico di bordo — promemoria", description: "Lista dimostrativa senza marca, quantità o ordine effettivo.", componentId: "spares", source: simulatedSource, status: "Da verificare", urgency: "Bassa", internalNotes: "Confermare specifiche prima dell'approvvigionamento.", demo: true },
  { id: "demo-020", date: "2026-09-20", type: "Nota tecnica", title: "Prossima verifica impianto e registri", description: "Promemoria scenario: confrontare manuali, misure, documenti originali e annotazioni del tecnico responsabile.", componentId: "general", source: simulatedSource, status: "Da verificare", urgency: "Media", internalNotes: "Nessun esito tecnico reale associato al record.", demo: true },
];

export const demoDisclaimer = "Tutti i record precaricati sono simulati: non sono rapporti di lavoro, fatture, DDT o prove di interventi realmente avvenuti.";
